### ISSUE TITLE
Enhanced time range options for "list" command 

### ISSUE THREAD

**Issue by svante-jonsson** [linusromland/TimeTrack#12]
Dear TimeTracker Development Team,

I hope this message finds you well. I've been using TimeTrack for time tracking over the past year and have found it immensely valuable for managing my tasks efficiently. First and foremost, I want to express my gratitude for the excellent work you've done so far.

As I've been actively using the "list" command to review my recorded time, I've identified an opportunity to enhance its functionality. The current options for specifying time ranges using `-s` and `-e` are great, but I believe expanding these options would significantly improve user experience and convenience.

Therefore, I propose the addition of new options/flags that allow users to easily specify common time ranges. Here are the suggested options:

### Last N Days

**Flag:** `-l` or `--last`

**Example:**

```sh
$ timetrack list -l 30 # This should list time entries from the last 30 days (including today)
```

### Specific Month

 **Flag:** `-m` or `--month`

**Example:**

```sh
$ timetrack list -m 11 # This should list time entries for the latest November
```

### Specific Year (addition to above month flag)

**Flag:** `-y` or `--year`

**Example:**

```sh
$ timetrack list -y 22 # This should list time entries for 2022
```

```sh
$ timetrack list -m 11 -y 22 # This should list time entries for November 2022
```

These additions would greatly streamline the process of retrieving specific sets of data, saving users time and effort. It aligns with the tool's goal of providing a flexible and efficient time tracking solution.

I believe this feature would not only enhance the functionality of TimeTrack but also contribute to its versatility for users with different time tracking needs.

Thank you for considering this feature request. I appreciate the hard work you put into making TimeTrack a valuable tool for users like me. If you have any questions or need further clarification, feel free to reach out.

Looking forward to seeing TimeTrack evolve with this exciting addition.

Kind regards,
Svante Jonsson

**Comment by linusromland** [comment]
Dear @svante-jonsson,

I hope this message finds you well. Thank you for your kind words and your continued support of TimeTrack. We greatly appreciate your feedback and are delighted to hear that TimeTrack has been valuable in helping you manage your tasks efficiently.

Your suggestion to enhance the "list" command with new options/flags for specifying time ranges is an excellent idea. We're always striving to improve our software and make it more user-friendly, and your input is invaluable in achieving that goal.

I am pleased to announce that your requested feature is now available in the latest release, TimeTrack version 0.3.1. We have added the "--next" and "--last" flags to the "list" command, which allow you to retrieve time entries for the next and last days from a specified start date. You can also specify the unit for these flags, such as "--last 30d," which will retrieve the last 30 days of data from the start date. This enhancement will undoubtedly streamline the process of retrieving specific sets of data and make TimeTrack even more efficient for users like you.

You can download the latest release, TimeTrack version 0.3.1, and explore these new features by visiting the following link: [https://github.com/linusromland/TimeTrack/releases/tag/v0.3.1](https://github.com/linusromland/TimeTrack/releases/tag/v0.3.1).

We are committed to continuously improving TimeTrack and providing a versatile time tracking solution for our users. Your feedback is instrumental in shaping the future of our software, and we are grateful for your contribution.

If you have any further suggestions or questions, please don't hesitate to reach out to us. We value your input and are here to assist you in any way we can.

Once again, thank you for your support, and we look forward to seeing TimeTrack evolve with this exciting addition.

Kind regards,

Linus Romland
TimeTrack Development Team
